site_name: Posting
site_url: https://posting.sh
repo_url: https://github.com/darrenburns/posting
repo_name: darrenburns/posting
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
  custom_dir: docs/overrides
  icon:
    logo: fontawesome/solid/paper-plane
  features:
    - search.suggest
    - search.highlight
    - header.autohide
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - tags
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - footnotes
  - tables
  - pymdownx.keys
