name: Test

on: [push, pull_request]
env:
    PYTEST_ADDOPTS: "--color=yes"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rye Python Setup
        uses: eifinger/setup-rye@v4
        with:
            version: '0.35.0'
      - name: Configure Virtual Environment
        run: |
            source .venv/bin/activate
            rye sync
      - name: Run Tests
        run: make test
      - name: Attach Code Coverage
        uses: py-cov-action/python-coverage-comment-action@v3.25
    
