name: Test

on: [push, pull_request]
env:
    PYTEST_ADDOPTS: "--color=yes"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rye Python Setup
        uses: eifinger/setup-rye@v4
        with:
            version: '0.35.0'
      - name: Install Dependencies
        run: rye sync
      - name: Run Tests
        run: |
            source .venv/bin/activate
            make test
      - name: Attach Code Coverage
        uses: py-cov-action/python-coverage-comment-action@v3.25
      - name: Save Snapshot Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot-report-posting
          path: snapshot_report.html
        # TODO - fix file system ordering, see latest snapshot report
    
